apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system  # ensures resources deploy here

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.8.4
    releaseName: my-metrics
    includeCRDs: true
    valuesFile: values.yaml
