apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.14.1
    releaseName: nginx
    includeCRDs: true
    valuesInline:
      controller:
        replicaCount: 1   # single-node cluster â†’ 1 replica
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet

        service:
          type: ClusterIP  # REQUIRED when using hostNetwork

        ingressClassResource:
          name: nginx
          default: true

        admissionWebhooks:
          enabled: true

      defaultBackend:
        enabled: false
