apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.8.4 # renovate: github-releases=cilium/cilium
    releaseName: "my-metrics"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml