apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.14.1
    releaseName: nginx
    includeCRDs: true
    valuesInline:
      controller:
        replicaCount: 1
        service:
          type: LoadBalancer       # <-- changed from NodePort
        ingressClassResource:
          default: true
      defaultBackend:
        enabled: false
