apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd   # ensures resources deploy here
resources:
  - ns.yaml
  - ingress.yaml
  - http-route.yaml
  - projects.yaml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.0.6
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml