apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  # - cloudflare-secret.yaml
  - cluster-issuer.yaml
  - validate-setup.yaml
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.19.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
