apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Gateway resources
  - gateway-class.yaml
  - ns.yaml
  - gateway-external.yaml
  - gateway-internal.yaml
  - cert-drogontech.yaml


generatorOptions:
  disableNameSuffixHash: true